config/routes.rb
College::Application.routes.draw do
  
  resources :menus

  devise_for :users, :path_prefix => 'd'
  resources :users
  
  resources :loc_categories
  resources :locations

  resources :divisions
  resources :conferences
  resources :teams

  resources :pages
  
  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
	  get "requests", :on => :collection
	  get "invites", :on => :collection
  end

  root :to => 'pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    # Currently  the following roles exist for a user
	#     :admin, conference, president, tailgater, author, banned
      user ||= User.new # guest user (not logged in)
      if user.role == "admin"
        can :manage, :all
      elsif user.role == "conference"
        can :manage, :all
      elsif user.role == "president"
        can :read, :all
      elsif user.role == "tailgater"
        can :read, :all
      elsif user.role == "author"
        can :read, :all
      elsif user.role == "banned"
        cannot :read, :any
      else
        can :read, :all
      end

    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  attr_accessible :name, :division_id
  
  belongs_to :division
  has_many :teams
  
  validates_presence_of :name
  validates_associated :division 
end

app/models/division.rb
class Division < ActiveRecord::Base
  attr_accessible :name
  
  has_many :conferences
  
  validates_presence_of :name
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  include Amistad::FriendshipModel
end

app/models/loc_category.rb
class LocCategory < ActiveRecord::Base
  attr_accessible :name, :location_id, :image
  
  has_and_belongs_to_many :locations
  belongs_to :menus
  
  validates_presence_of :name
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :address, :city, :state, :zip, :loc_category_ids, :team_ids
  
  has_and_belongs_to_many :teams
  has_and_belongs_to_many :loc_categories
  
  validates_presence_of :name
  validates_associated :teams, :loc_categories
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :user_id, :items, :loc_category_ids
  
  belongs_to :users
  has_many :loc_categories
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :name, :permalink, :content
  
  validates_presence_of :name, :permalink, :content
  validates :permalink, :uniqueness => true
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :nickname, :shortname, :street, :city, :state, :zip, :conference_id, :location_id
  
  belongs_to :conference
  has_and_belongs_to_many :locations
  has_many :users
  
  validates_presence_of :name
  validates_associated :conference
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :team
  has_one :menu
  # Define roles
  ROLES = %w[admin conference president tailgater author banned]

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
  				  :role, :avatar, :team_id, :crop_x, :crop_y, :crop_w, :crop_h
  #Include uploader
  mount_uploader :avatar, AvatarUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar
  
  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
  
  include Amistad::FriendModel
end

app/controllers/loc_categories_controller.rb
class LocCategoriesController < ApplicationController
  load_and_authorize_resource
  
  # commented out instance variables because load and authorize takes care of this for me
  
  def index
    @loc_categories = LocCategory.all
  end

  def show
    # @loc_category = LocCategory.find(params[:id])
  end

  def new
   #  @loc_category = LocCategory.new
  end

  def create
    # @loc_category = LocCategory.new(params[:loc_category])
    if @loc_category.save
      redirect_to loc_category_path, :notice => "Successfully created location category."
    else
      render :action => 'new'
    end
  end

  def edit
    # @loc_category = LocCategory.find(params[:id])
  end

  def update
    # @loc_category = LocCategory.find(params[:id])
    if @loc_category.update_attributes(params[:loc_category])
      redirect_to @loc_category, :notice  => "Successfully updated location category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    # @loc_category = LocCategory.find(params[:id])
    @loc_category.destroy
    redirect_to loc_categories_url, :notice => "Successfully destroyed location category."
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  load_and_authorize_resource

  def index
    @menus = Menu.all
  end

  def show
  end

  def new
    @loc_categories = LocCategory.all
  end

  def create
    if @menu.save
      redirect_to @menu, :notice => "Successfully created menu."
    else
      render :action => 'new'
    end
  end

  def edit
    @loc_categories = LocCategory.all
  end

  def update
     params[:location][:loc_category_ids] ||= []
    if @menu.update_attributes(params[:menu])
      redirect_to @menu, :notice  => "Successfully updated menu."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @menu.destroy
    redirect_to menus_url, :notice => "Successfully destroyed menu."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/loc_categories_helper.rb
module LocCategoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/loc_categories/_form.html.erb
<%= simple_form_for @loc_category, :html => { :class => 'form-horizontal', :multipart =>true } do |f| %>
  <fieldset> 
    <%= f.input :name %>
    <%= f.file_field :image, :label => 'Category image' %>
  	<div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', loc_categories_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/loc_categories/edit.html.erb
<% title "Edit Location Category" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @loc_category %> |
  <%= link_to "View All", loc_categories_path %>
</p>

app/views/loc_categories/index.html.erb
<% title "Location Categories" %>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Name</th>
    <th class="actions">Actions</th>
  </tr>
  <% for loc_category in @loc_categories %>
    <tr>
      <td><%= link_to loc_category.name, edit_loc_category_path(loc_category) %></td>
      
      <td>
          <%= link_to loc_category, :class =>'btn' do %>
			<i class="icon-eye-open"></i>
		  <% end %>
		  
		  <%= link_to edit_loc_category_path(loc_category), :class =>'btn' do %>
			<i class="icon-edit"></i>
		  <% end %>
		  
		  <%= link_to loc_category, :confirm => 'Are you sure?', :method => :delete, :class =>'btn btn-danger' do %>
			<i class="icon-trash icon-white"></i>
		  <% end %>
      </td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location Category", new_loc_category_path, :class =>'btn btn-primary' %></p>

app/views/loc_categories/new.html.erb
<% title "New Location Category" %>

<%= render 'form' %>

<p><%= link_to "Back to List", loc_categories_path %></p>

app/views/loc_categories/show.html.erb
<% title "Location Category" %>

<p>
  <strong>Name:</strong>
  <%= @loc_category.name %>
</p>

<p>
  <% if can? :update, @loc_category %>
  	<%= link_to "Edit", edit_loc_category_path(@loc_category) %> |
  <% end %>
  <% if can? :destroy, @loc_category %>
    <%= link_to "Destroy", @loc_category, :confirm => 'Are you sure?', :method => :delete %> |
  <% end %>	
  <%= link_to "View All", loc_categories_path %>
</p>